name: run tests mac

on:
  push:
    branches:
      - develop
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        script: ["./test.sh", "./bench.sh"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - run: ${{ matrix.script }}
