name: run tests windows

on:
  push:
    branches:
      - develop
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - run: cargo test -- --nocapture
      - run: cargo test --manifest-path test/Cargo.toml -- --nocapture
      - run: cd test && cargo bench
